spring:
  profiles:
    active: "local"
  application:
    name: registration-server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 8762